apiVersion: apps/v1
kind: Deployment
metadata:
  name: aksforspringapplication-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aksforspringapplication
  template:
    metadata:
      labels:
        app: aksforspringapplication
    spec:
      containers:
      - name: aksforspringapplication
        image: acrsample1.azurecr.io/bhanu9505508737/aksforspringapplication:#{Build.BuildId}#
        ports:
        - containerPort: 80
        env:
          - name: PODNAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
      imagePullSecrets:
      - name: bhanu97
---
apiVersion: v1
kind: Service
metadata:
  name: aksforspringapplication
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: aksforspringapplication
